FROM fluent/fluentd:v1.10-1
MAINTAINER Pierre Joseph <josephierres@hotmail.com>

USER root
ENV FLUENTD_CONF="fluent.conf"
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 # customize following instruction as you wish
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem install fluent-plugin-memcached -v 0.2.0 --no-rdoc --no-ri
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /home/fluent/.gem/ruby/2.5.0/cache/*.gem

 RUN buildDeps="sudo make gcc g++ libc-dev" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo apt-get install -y default-libmysqlclient-dev \
 && sudo gem install fluent-plugin-mysql \
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
 apt-get purge -y --auto-remove \
 -o APT::AutoRemove::RecommendsImportant=false \
 $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
COPY ./configs/fluent.conf /fluentd/etc/
COPY entrypoint.sh /bin/

USER fluent
EXPOSE 24224 5140