environment: production
namespace: bbl
app: biblio
replicas: 3
container:
  name: prd-biblio-mysql
  port: 3306
  image: mysql
  tag: 8.3
  imagePullPolicy: "IfNotPresent"
  containerSecurityContext:
    runAsUser: 1001
    runAsNonRoot: true
  podSecurityContext:
    fsGroup: 1001
db:
  name: biblio
  rootpassword: password
  user: user
  userpassword: password
  initializationFiles:
    db.sh: |-
      #!/bin/sh
      mysqldump -h remoteDbUrl -u remoteUser -pRemotePass --databases db1 db2 > /var/lib/mysql/dump.sql
      mysql -uroot -pmyPass < /var/lib/mysql/dump.sql
      rm /var/lib/mysql/dump.sql
      echo "GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' IDENTIFIED BY 'myPass';" | mysql -uroot -pmyPass

pvc:
  volume: mysql-pv
  permissions: mysql-pv-permissions
  path: /data/mysql-volume
  claim: mysql-pv-claim