apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bbl
  name: flask-mysql
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaskapp
        tier: mysql
    spec:
      containers:
      - image: mysql:8.3
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: gestion_bibliotheque
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config