apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: bbl
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
    tier: mysql 
  clusterIP: None
