apiVersion: v1
kind: Service
metadata:
  name: flask-mysql
  namespace: bbl
  labels:
    app: flaskapp
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: flaskapp
    tier: mysql 
  clusterIP: None
