version: '3.8'
services:
  biblio:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
    depends_on:
      - mysql
      - redis
      - otel-collector
      - prometheus
      - grafana
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: biblio_app
    networks:
      - biblio_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - biblio
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx
    networks:
      - biblio_net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pharmacy_management
      MYSQL_USER: pharma_user
      MYSQL_PASSWORD: pharma_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - biblio_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: mysql

  redis:
    image: redis:latest
    networks:
      - biblio_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redis

  fluentd:
    image: fluent/fluentd:v1.12
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/configs/fluentd.conf:/fluentd/etc/fluent.conf
    networks:
      - biblio_net

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - biblio_net

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC for traces
    networks:
      - biblio_net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - biblio_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - jaeger
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - biblio_net

networks:
  biblio_net:

volumes:
  mysql_data:
  grafana_data:
