version: '1.0'

services:
   
  # WSIG et Flask sur python avec WSGI
  wsgi:
    build: ./wsgi
    container_name: wsgi
    restart: always
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - APP_NAME=Bibliotheque
    working_dir: /app
    volumes:
     - './wsgi:/app'
    command: [ "uwsgi", "--ini", "app.ini" ]
    expose:
      - 8080        
    networks:
      - 'bibliotheque'

  nginx:
    build: ./nginx
    container_name: nginx  
    restart: always
    volumes:
      - './nginx/www:/var/www/html'    # si toutefois j'ai des statics files
    ports:
      - '8000:80' # nginx utilise le port 80
    depends_on:
      - wsgi
    networks:
      - 'bibliotheque'  
networks:
  bibliotheque:
    driver: bridge  

