
services:
  # Serveur de base de données MySQL
  mysql:
    image: mysql:8.0.22   
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password    
    restart: always   
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestion_bibliotheque
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./mysql/app:/app
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 20s
      retries: 10
    

  # Serveur de cache Redis
  redis:
    container_name: redis
    image: redis:7.2.4    
    ports:
      - '6378:6379'
    volumes:
      - ./redis/data:/data
  

  # Application WSGI (Flask)
  wsgi:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    image: wsgi:1.0
    container_name: wsgi
    restart: always
    volumes:
      - ./myapp:/app
    working_dir: /app
    environment:
      - MYSQL_PORT=3306
      - FLASK_ENV=production
      - APP_NAME=Bibliotheque
      - REDIS_URL=redis://redis:6379/0 
      
        
    ports:
     - '5002:5002'  
    expose:
      - 8080
      - 5000
    depends_on:
      - mysql
      - redis
      # - otelcol
   #   - prometheus
   #  - grafana
   

  # Serveur Nginx
  nginx:
    # build:
    #     context: ./nginx
    #     dockerfile: Dockerfile
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes: 
      # - './nginx/configs/opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf'
      - './nginx/configs/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/www:/var/www/html'
      - './nginx/log:/var/log/nginx'
    ports:
      - '8000:80'
    depends_on:
      - wsgi   