receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:      #j'ai vu des miseres `a cause de cela`
          allowed_origins:
exporters:
  # debug:
  #   verbosity: detailed
  otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: https://jaeger.example.com:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  fluentforward:
    endpoint: "fluentd:24224"
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
  alertmanager:
    endpoint: "http://alertmanager:9093/api/v1/alerts"
extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, jaeger, elasticsearch]
      
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, loki]