apiVersion: apps/v1
kind: Deployment
metadata:  
  namespace: bbl
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp     
  template:
    metadata:
      labels:
        app: flaskapp       
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379