apiVersion: apps/v1
kind: Deployment
metadata:  
  namespace: bbl
  name: flask-redis
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
      tier: redis
  strategy:
    type: Recreate     
  template:
    metadata:
      labels:
        app: flaskapp 
        tier: redis      
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379