apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bbl
  labels:
    app: bbl-redis
spec:
  selector:
    matchLabels:
      app: redis     
  template:
    metadata:
      labels:
        app: redis       
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379