apiVersion: v1
kind: Service
metadata:
  name: flask-redis
  namespace: bbl
  labels:
    app: bbl-redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
  clusterIP: None