apiVersion: v1
kind: Service
metadata:
  name: flask-redis
  namespace: bbl
  labels:
    app: flaskapp    
    tier: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: flaskapp    
    tier: redis
  clusterIP: None