apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: bbl
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      # nodePort: 30007
  #type: NodePort
  selector:
    app: redis
    tier: redis
    #clusterIP: None