apiVersion: v1
kind: Service
metadata:
  name: redis-biblio-service
  namespace: bbl
  labels:
    app: flaskapp
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 30007
  type: NodePort
  selector:
    app: flaskapp
    tier: redis
  #clusterIP: None