kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: bbl
data:
  default.conf: |
        


        upstream wsgi_servers {
            #server flaskapp:8080;     # chaque services avec leurs ports
         
            server localhost:8080;
        }

        server {
            listen 80;

            location / {
                include uwsgi_params;
                uwsgi_pass wsgi_servers;
            }
      
        }
