apiVersion: v1
kind: Service
metadata:
  name: nginx-biblio-service
  namespace: bbl
  labels:
    app: flaskapp
spec:
  
  selector:
    app: flaskapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
    name: http
  type: NodePort