apiVersion: v1
kind: Service
metadata:
  name: flask-nginx
  namespace: bbl
  labels:
    app: flask-nginx
spec:
  type: LoadBalancer
  selector:
    app: flask-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http