FROM prom/prometheus
ADD prometheus.yml /etc/prometheus/
# set environment variables
ENV TZ=CANADA/OTTAWA

# expose the Prometheus server port
EXPOSE 9090

# set the entrypoint command
# --log.level=info           Only log messages with the given severity or above. One of: [debug, info, warn, error]
# --log.format=logfmt        Output format of log messages. One of: [logfmt, json]
ENTRYPOINT [ "prometheus", \
             "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--storage.tsdb.retention=365d", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles", \
             "--web.external-url=http://localhost:9090", \
             "--log.level=info", \
             "--log.format=json" ] 