global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flask_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["biblio:8000"]

  - job_name: "mysql"
    metrics_path: /metrics
    static_configs:
      - targets: ["mysql:9104"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  - job_name: "fluentd"
    static_configs:
      - targets: ["fluentd:24224"]
