apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bbl
helmGlobals:
  chartHome: /mysql
secretGenerator:
- name: mysql-root-password
  literals:
  - password=password
resources:
  - namespace-bbl.yaml
  - mysql/sc-mysql.yaml
  - mysql/pv-mysql.yaml
  # - sc-app.yaml
  # - pv-app.yaml


 