apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: {{ .Values.cm.name }}
              mountPath: {{ .Values.cm.path }}
            - name: {{ .Values.pvc.volume }}
              mountPath: {{ .Values.pvc.path }}
      volumes:
        - name: {{ .Values.cm.name }}
          configMap:
            name: {{ .Values.cm.name }}
        - name: {{ .Values.pvc.volume }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claim }}
