FROM grafana/grafana:8.3.7
# ENV Variables for cofiguration
ENV GF_AUTH_ANONYMOUS_ENABLED=true #Enabled the Anonymous user no user/pass needed
ENV GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer #Activate the ROLE VIEWER as Default
ENV GF_AUTH_BASIC_ENABLED=false #Disable the AUTH Method
ENV GF_AUTH_DISABLE_LOGIN_FORM=true #Disable the login on show
ENV GF_AUTH_DISABLE_SIGNOUT_MENU=true #Diabled the menu
ENV GF_SECURITY_ALLOW_EMBEDDING=true #Allow IFRAME Calls
ENV GF_SERVER_SERVE_FROM_SUB_PATH=true  
ENV GF_SERVE_FROM_SUB_PATH=true

EXPOSE 3000

ADD ./provisioning /etc/grafana/provisioning #Add the configuration
ADD ./dashboards /var/lib/grafana/dashboards #Add the Dashboard


CMD [ "grafana-reporter" ]