apiVersion: v1
kind: Service
metadata:
  name: mysql-biblio-service
  namespace: bbl
  labels:
    app: flaskapp
spec:
  ports:
    - port: 3306
      # protocol: TCP
      # targetPort: 3306
      # nodePort: 30006
  #type: NodePort
  selector:
    app: flaskapp
    tier: mysql
    clusterIP: None