---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: wsgi-biblio    
    app: flaskapp
    tier: frontend
  name: wsgi-biblio
  namespace: bbl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaskapp
        tier: frontend
    spec:
      containers:
      - name: flask-uwsgi
        image: debuggerboy/uwsgi:v1.0.3
        imagePullPolicy: Always
        command: ["uwsgi"]
        args: ["--ini", "/uwsgi.ini"]
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        volumeMounts:
        - name: uwsgi-config-volume
          mountPath: /uwsgi.ini
          subPath: uwsgi.ini
        - name: www-storage
          mountPath: /srv/app/
     
      initContainers:
      - name: layering
        image: debuggerboy/uwsgi:v1.0.3
        imagePullPolicy: Always
        volumeMounts:
        - name: start-config-volume
          mountPath: /start.sh
          subPath: start.sh
        - name: www-storage
          mountPath: /srv/app/
        command:
        - "bash"
        - "/start.sh"
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: app-pvc
      - name: uwsgi-config-volume
        configMap:
          name: uwsgi-config
      
      - name: start-config-volume
        configMap:
          name: start-config