apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: bbl
  labels:
    app: flaskapp
spec:
  type: NodePort
  ports:
    - port: 8001
      protocol: TCP
      name: http
      targetPort: 8001
      # nodePort: 30009
  
  selector:
    app: flaskapp
    tier: frontend
  