apiVersion: v1
kind: Service
metadata:
  name: wsgi-biblio-service
  namespace: bbl
  labels:
    app: flaskapp
spec:
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
      nodePort: 30009
  type: NodePort
  selector:
    app: flaskapp
    tier: frontend
  #clusterIP: None