# utiliser l´image Python3.12.1 du conteneur
FROM python:3.10
WORKDIR /app
ADD ./requirements.txt /app
RUN pip install --upgrade pip
# installer les dependances à Python
RUN pip install --no-cache-dir -r requirements.txt
CMD [ "uwsgi", "--ini", "app-0.ini"] 
