---
kind: ConfigMap
apiVersion: v1
metadata:
  name: uwsgi-config
data:
  uwsgi.ini: |
    [uwsgi]
    wsgi-file = wsgi.py
    #WSGI module and Callable app
    virtualenv = /app/public/.venv/
    chdir = /app/public/
    callable = app
    module = main
    callable = app
    plugins = python3
    #User ID for nginx config
    uid = www-data
    #Group ID for nginx config
    gid = www-data
    #Serve as Master
    master = true
    #processes = Number of Process
    processes = 3
    #Socket path of WSGI
    socket = :8001
    #Listen on TCP socket
    #http = 0.0.0.0:8080
    #Modified Permissions
    chmod-sock = 664
    #Graceful reloading
    lazy=true
    #Auto cleanup the socket
    vacuum = true
    #For expected process signals at startup
    die-on-term = true
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: start-config
data:
  start.sh: |
    #!/bin/bash
    shopt -s extglob 
    cd /app/
    rm -rf publics
    git clone -b projet3 https://github.com/josephpierres/MGL7760-H2024-Projet1-Groupe-1.git /app/publics    
    mv publics/k8s/data/wsgi/ /public/
    rm -rf publics 
    cd /app/public            
    /usr/bin/python3 -m venv .venv
    source .venv/bin/activate
    pip install --upgrade pip
    pip install --no-cache-dir -r requirements.txt
    shopt -u extglob 

    #   #!/bin/bash #############################################
    # shopt -s extglob 
    # cd /app/
    # rm -rf publics
    # git clone -b projet3 https://github.com/josephpierres/MGL7760-H2024-Projet1-Groupe-1.git /app/publics
    # #find ./publics -mindepth 1 ! -regex '^./publics/k8s/data/wsgi\(/.*\)?' -delete
    # mv publics/k8s/data/wsgi public
    # rm -rf publics 
    # cd /app/public   
    # # rm -rf !(k8s)
    # # cp -r k8s/data/wsgi/* .
    # # rm -rf k8s       
    # /usr/bin/python3 -m venv .venv
    # source .venv/bin/activate
    # pip install --upgrade pip
    # pip install --no-cache-dir -r requirements.txt
    # shopt -u extglob 