---
kind: ConfigMap
apiVersion: v1
metadata:
  name: uwsgi-config
data:
  uwsgi.ini: |
    [uwsgi]
    wsgi-file = wsgi.py
    #WSGI module and Callable app
    virtualenv = /app/.venv/
    chdir = /app/
    callable = app
    module = main
    callable = app
    plugins = python3
    #User ID for nginx config
    uid = www-data
    #Group ID for nginx config
    gid = www-data
    #Serve as Master
    master = true
    #processes = Number of Process
    processes = 3
    #Socket path of WSGI
    socket = :8001
    #Listen on TCP socket
    #http = 0.0.0.0:8080
    #Modified Permissions
    chmod-sock = 664
    #Graceful reloading
    lazy=true
    #Auto cleanup the socket
    vacuum = true
    #For expected process signals at startup
    die-on-term = true
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: start-config
data:
  start.sh: |
    #!/bin/bash
    cd /app
    git clone https://github.com/josephpierres/MGL7760-H2024-Projet1-Groupe-1.git /app    
    shopt -s extglob
    echo " effacer tout sauf le repertoire wsgi"
    find . -mindepth 1 -maxdepth 1 ! -name 'wsgi' -exec rm -rf {} +  
    # copier le contenu du wsgi dans le public
    cp -r /wsgi/* .
    echo "eliminer le wsgi"
    rm -rf wsgi
    shopt -u extglob
    /usr/bin/python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt