apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: bbl
  labels:
    app: flaskapp
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP      
      targetPort: 8080
     
  
  selector:
    app: flaskapp
   
  