# utiliser l´image Python3.12.1 du conteneur
FROM python:3.10

# repertoire de travail à /app
WORKDIR /app

# copier les conteuns du repertoire courrant dans le repertoire /app du conteneur
ADD ./requirements.txt /app

# installer les dependances à Python
RUN pip install --no-cache-dir -r requirements.txt

#COPY . .
# execute la commande d´execution de flask

# CMD [ "uwsgi", "app.ini"]
