# utilise l´image de Nginx1.13
FROM nginx

# effacer la configuration par defaut 
RUN rm /etc/nginx/conf.d/default.conf

#copier le default.conf du repertoire courrant dans le conteneur Nginx
COPY /configs/default.conf /etc/nginx/conf.d/