apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: bbl
spec:
  storageClassName: mysql-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql-volume
