{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "job", "query": "biblio_api" }
  ]
 },
 "panels": [
  { "title": "Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success and error requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status!=\"5xx\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status=\"5xx\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"$job\", status=~\"2.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"$job\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{job=\"$job\", status=~\"5.*\", handler!=\"/metrics\"}) / sum by(handler) (http_requests_total{job=\"$job\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"$job\"} / http_request_duration_seconds_count{job=\"$job\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{job=\"$job\",handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{job=\"$job\",handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"$job\",handler!=\"none\"} / http_request_duration_seconds_count{job=\"$job\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{job=\"$job\",le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count{job=\"$job\"}[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}